### ISSUE TITLE
Installer does not respect DB prefix

### ISSUE THREAD

**Issue by robertem128** [Web-Feet/coasterframework#18]
This only happens when installing the framework to an existing Laravel project, seems to work fine when installing the full CMS package.

**Comment by chadanuk** [comment]
Good spot - we'll look into it.

**Comment by neil-jennings** [comment]
install will now check and only show the field if a db prefix can be set it the .env file
by default the coaster cms package has a modified the config/database.php file with the prefix set to env('DB_PREFIX', '')
