### ISSUE TITLE
Admin Page module

### ISSUE THREAD

**Issue by ghost** [Web-Feet/coasterframework#40]
you made a really powerfull Page Manager

wish you made it seperate page package for laravel that we could use in our existing project

**Comment by neil-jennings** [comment]
Thanks, we do intend to make things more modular over time, however it may be a while before we get round to splitting up the page manager as it is the core of the system.

Which bits in particular are you interested in using in your project ?

**Comment by chadanuk** [comment]
@laravelish @neil-jennings We've been thinking about this and we're pretty sure you could use Coaster as a standalone page manager in any project by overriding the routes in the application you're building - the only bit that might be tricky is the Auth guard (#48)

So we're going to close this but we'll still be working on it - just from a different angle as technically it's possible but there may be some customisation / overriding needed of Coaster's authentication system and routes.
