### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by chadanuk** [Web-Feet/coasterframework#53]

**Comment by SarajevoNo1** [comment]
Hi Chardwik what is this for "add test" ?

thanks

**Comment by chadanuk** [comment]
Coaster currently doesn't have any TDD elements. 

We would like to start introducing this to ensure that updates/ upgrades don't affect existing deployments and to help focus development.

**Comment by SarajevoNo1** [comment]
Ok. Super. :;) thanks..good.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by chadanuk** [comment]
Test suite added - test just need fleshing out
