### ISSUE TITLE
$page->id not defined when accessed in a subpage template

### ISSUE THREAD

**Issue by Dannymx** [Web-Feet/coasterframework#63]
According to [the docs](https://www.coastercms.org/docs/developer/views/categories-and-filtering) in the categories and filtering, when looping through the subpages you should be able to get the ID of each page, but `$page->id` seems to be not defined, other variables as name, url, work just fine.

For now I had to go to the `PageDetails.php` file in the libraries and add it myself so I could get `$page->id` working.

**Comment by neil-jennings** [comment]
I've updated PageDetails.php to include the $id var now so it's a more compatible with the existing docs.
Still working on some brand new docs, hopefully ready in the next month or two.
