### ISSUE TITLE
[Question] Planning on updating to Laravel 5.5?

### ISSUE THREAD

**Issue by Naoray** [Web-Feet/coasterframework#64]
moved from: https://github.com/Web-Feet/coastercms/issues/69

Hello there,

are you planning on updating the whole project to Laravel 5.5?

Regards,
Naoray

**Comment by chadanuk** [comment]
Hi @Naoray,

Yes. We are. Hopefully soonish.

**Comment by Naoray** [comment]
@chadanuk do you have a specific date in mind?

**Comment by chadanuk** [comment]
Not currently but I don't think it will actually take too long to implement so once we find some time to work on it it shouldn't be too long before it's up.
