### ISSUE TITLE
install

### ISSUE THREAD

**Issue by sebalaini** [Web-Feet/coasterframework#73]
is this repo compatible with Laravel 5.8?
What happens with the full repo? has been abandoned and you are pushing more on this repo?

**Comment by chadanuk** [comment]
Yes. It is compatible, the package hasn't been abandoned but work has slowed massively since there have been some employment changes with those of us who work on it. We do intend to upgrade it and get it working with 5.8 by default. But time resources are a limiter here.

**Comment by sebalaini** [comment]
thanks :) I'll give it a try and see if I can use the CMS editor as in the package doesn't work.
I opened an issue, I don't know if it's normal or not.
