### ISSUE TITLE
Laravel 5.8 install

### ISSUE THREAD

**Issue by sebalaini** [Web-Feet/coasterframework#74]
As you said that it's compatible with Laravel 5.8 I've tried to install it on a fresh 5.8 Laravel installation and I cannot install this framework.

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: remove laravel/framework v5.8.14
    - Conclusion: don't install laravel/framework v5.8.14
    - Conclusion: don't install laravel/framework v5.8.13
    - Conclusion: don't install laravel/framework v5.8.12
    - Conclusion: don't install laravel/framework v5.8.11
    - Conclusion: don't install laravel/framework v5.8.10
    - Conclusion: don't install laravel/framework v5.8.9
    - Conclusion: don't install laravel/framework v5.8.8
    - Conclusion: don't install laravel/framework v5.8.7
    - Conclusion: don't install laravel/framework v5.8.6
    - Conclusion: don't install laravel/framework v5.8.5
    - Conclusion: don't install laravel/framework v5.8.4
    - Conclusion: don't install laravel/framework v5.8.3
    - Conclusion: don't install laravel/framework v5.8.2
    - Conclusion: don't install laravel/framework v5.8.1
    - Conclusion: don't install laravel/framework v5.8.0
    - web-feet/coasterframework v5.5.0 requires laravelcollective/html 5.5.* -> satisfiable by larav                                                                                     elcollective/html[5.5.x-dev, v5.5, v5.5.1, v5.5.2, v5.5.3, v5.5.4].
    - web-feet/coasterframework v5.5.1 requires laravelcollective/html 5.5.* -> satisfiable by larav                                                                                     elcollective/html[5.5.x-dev, v5.5, v5.5.1, v5.5.2, v5.5.3, v5.5.4].
    - web-feet/coasterframework v5.5.10 requires laravelcollective/html 5.5.* -> satisfiable by lara                                                                                     velcollective/html[5.5.x-dev, v5.5, v5.5.1, v5.5.2, v5.5.3, v5.5.4].
    - web-feet/coasterframework v5.5.11 requires laravelcollective/html 5.5.* -> satisfiable by lara                                                                                     velcollective/html[5.5.x-dev, v5.5, v5.5.1, v5.5.2, v5.5.3, v5.5.4].
    - web-feet/coasterframework v5.5.12 requires laravelcollective/html 5.5.* -> satisfiable by lara                                                                                     velcollective/html[5.5.x-dev, v5.5, v5.5.1, v5.5.2, v5.5.3, v5.5.4].
    - web-feet/coasterframework v5.5.13 requires laravelcollective/html 5.5.* -> satisfiable by lara                                                                                     velcollective/html[5.5.x-dev, v5.5, v5.5.1, v5.5.2, v5.5.3, v5.5.4].
    - web-feet/coasterframework v5.5.14 requires laravelcollective/html 5.5.* -> satisfiable by lara                                                                                     velcollective/html[5.5.x-dev, v5.5, v5.5.1, v5.5.2, v5.5.3, v5.5.4].
    - web-feet/coasterframework v5.5.15 requires laravelcollective/html 5.5.* -> satisfiable by lara                                                                                     velcollective/html[5.5.x-dev, v5.5, v5.5.1, v5.5.2, v5.5.3, v5.5.4].
    - web-feet/coasterframework v5.5.2 requires laravelcollective/html 5.5.* -> satisfiable by larav                                                                                     elcollective/html[5.5.x-dev, v5.5, v5.5.1, v5.5.2, v5.5.3, v5.5.4].
    - web-feet/coasterframework v5.5.3 requires laravelcollective/html 5.5.* -> satisfiable by larav                                                                                     elcollective/html[5.5.x-dev, v5.5, v5.5.1, v5.5.2, v5.5.3, v5.5.4].
    - web-feet/coasterframework v5.5.4 requires laravelcollective/html 5.5.* -> satisfiable by larav                                                                                     elcollective/html[5.5.x-dev, v5.5, v5.5.1, v5.5.2, v5.5.3, v5.5.4].
    - web-feet/coasterframework v5.5.5 requires laravelcollective/html 5.5.* -> satisfiable by larav                                                                                     elcollective/html[5.5.x-dev, v5.5, v5.5.1, v5.5.2, v5.5.3, v5.5.4].
    - web-feet/coasterframework v5.5.6 requires laravelcollective/html 5.5.* -> satisfiable by larav                                                                                     elcollective/html[5.5.x-dev, v5.5, v5.5.1, v5.5.2, v5.5.3, v5.5.4].
    - web-feet/coasterframework v5.5.7 requires laravelcollective/html 5.5.* -> satisfiable by larav                                                                                     elcollective/html[5.5.x-dev, v5.5, v5.5.1, v5.5.2, v5.5.3, v5.5.4].
    - web-feet/coasterframework v5.5.8 requires laravelcollective/html 5.5.* -> satisfiable by larav                                                                                     elcollective/html[5.5.x-dev, v5.5, v5.5.1, v5.5.2, v5.5.3, v5.5.4].
    - web-feet/coasterframework v5.5.9 requires laravelcollective/html 5.5.* -> satisfiable by larav                                                                                     elcollective/html[5.5.x-dev, v5.5, v5.5.1, v5.5.2, v5.5.3, v5.5.4].
    - laravelcollective/html 5.5.x-dev requires illuminate/view 5.5.* -> satisfiable by illuminate/v                                                                                     iew[5.5.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.3                                                                                     7, v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44].
    - laravelcollective/html v5.5 requires illuminate/view 5.5.* -> satisfiable by illuminate/view[5                                                                                     .5.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37, v5                                                                                     .5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44].
    - laravelcollective/html v5.5.1 requires illuminate/view 5.5.* -> satisfiable by illuminate/view                                                                                     [5.5.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37,                                                                                      v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44].
    - laravelcollective/html v5.5.3 requires illuminate/view 5.5.* -> satisfiable by illuminate/view                                                                                     [5.5.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37,                                                                                      v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44].
    - laravelcollective/html v5.5.4 requires illuminate/view 5.5.* -> satisfiable by illuminate/view                                                                                     [5.5.x-dev, v5.5.0, v5.5.16, v5.5.17, v5.5.2, v5.5.28, v5.5.33, v5.5.34, v5.5.35, v5.5.36, v5.5.37,                                                                                      v5.5.39, v5.5.40, v5.5.41, v5.5.43, v5.5.44].
    - laravelcollective/html v5.5.2 requires illuminate/view 5.6.* -> satisfiable by illuminate/view                                                                                     [5.6.x-dev, v5.6.0, v5.6.1, v5.6.10, v5.6.11, v5.6.12, v5.6.13, v5.6.14, v5.6.15, v5.6.16, v5.6.17,                                                                                      v5.6.19, v5.6.2, v5.6.20, v5.6.21, v5.6.22, v5.6.23, v5.6.24, v5.6.25, v5.6.26, v5.6.27, v5.6.28, v5                                                                                     .6.29, v5.6.3, v5.6.30, v5.6.31, v5.6.32, v5.6.33, v5.6.34, v5.6.35, v5.6.36, v5.6.37, v5.6.38, v5.6                                                                                     .39, v5.6.4, v5.6.5, v5.6.6, v5.6.7, v5.6.8, v5.6.9].
    - don't install illuminate/view 5.5.x-dev|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.5.0|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.5.16|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.5.17|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.5.2|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.5.28|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.5.33|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.5.34|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.5.35|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.5.36|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.5.37|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.5.39|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.5.40|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.5.41|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.5.43|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.5.44|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view 5.6.x-dev|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.6.0|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.6.1|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.6.10|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.6.11|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.6.12|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.6.13|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.6.14|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.6.15|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.6.16|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.6.17|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.6.19|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.6.2|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.6.20|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.6.21|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.6.22|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.6.23|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.6.24|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.6.25|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.6.26|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.6.27|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.6.28|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.6.29|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.6.3|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.6.30|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.6.31|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.6.32|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.6.33|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.6.34|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.6.35|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.6.36|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.6.37|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.6.38|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.6.39|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.6.4|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.6.5|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.6.6|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.6.7|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.6.8|don't install laravel/framework 5.8.x-dev
    - don't install illuminate/view v5.6.9|don't install laravel/framework 5.8.x-dev
    - Installation request for laravel/framework 5.8.* -> satisfiable by laravel/framework[5.8.x-dev                                                                                     , v5.8.0, v5.8.1, v5.8.10, v5.8.11, v5.8.12, v5.8.13, v5.8.14, v5.8.2, v5.8.3, v5.8.4, v5.8.5, v5.8.                                                                                     6, v5.8.7, v5.8.8, v5.8.9].
    - Installation request for web-feet/coasterframework 5.5.* -> satisfiable by web-feet/coasterfra                                                                                     mework[v5.5.0, v5.5.1, v5.5.10, v5.5.11, v5.5.12, v5.5.13, v5.5.14, v5.5.15, v5.5.2, v5.5.3, v5.5.4,                                                                                      v5.5.5, v5.5.6, v5.5.7, v5.5.8, v5.5.9].`

**Comment by chadanuk** [comment]
@neil-jennings Any thoughts on this - I think it would be pretty easy to resolve this?
