### ISSUE TITLE
different form template

### ISSUE THREAD

**Issue by sebalaini** [Web-Feet/coasterframework#75]
I need to create a different form layout to book a training, here the result I want.

http://www.buchanancomputing.net/events_layout.html?IDX=401&q=2019

how can I add a new block, and how can I manage the form?

I created a new folder in the blocks with a new form layout inside but I cannot call it.

![formPNG](https://user-images.githubusercontent.com/17096352/57071314-f66fd680-6cd1-11e9-9870-444720ce0dbc.PNG)

P.S. I've already asked to join the Slack community but I haven't been accepted yet.

**Comment by chadanuk** [comment]
@sebalaini the form blade file should be in the "form" folder.. All forms go in that folder. Then when you review block changes on the theme in the admin it should be available to you as a form.

**Comment by sebalaini** [comment]
Ok, now it works, before wasn't working.

how can I insert again the old value in case it fail the submission due to the captcha? in Laravel I use `value="{{ old('name') }}"` but seems to don't work here

**Comment by chadanuk** [comment]
You can use `request()->input('name', '')`

**Comment by sebalaini** [comment]
Thanks :)
