### ISSUE TITLE
custom email

### ISSUE THREAD

**Issue by sebalaini** [Web-Feet/coasterframework#76]
how can I modify the mail template? where is the config?

**Comment by sebalaini** [comment]
actually, a better question is can I use pure laravel on the templates? and in the logic? can I create controllers for routes or forms?

**Comment by chadanuk** [comment]
@sebalaini Sorry for delay been a crazy few days!

It is completely possible, I guess  it depends on what you want. Coaster can handle all the form stuff or build a section and add you form there and use Laravel as per usual in that form

**Comment by sebalaini** [comment]
no problem, OK so I can use pure Laravel and use blade templates together with CMS template and add routes in the web.php in the routes folder?

**Comment by chadanuk** [comment]
@sebalaini Yup, the forms stuff is there to be a quick way to build basic forms. You can create custom email templates by using the same pattern as in the example 2017 theme (https://github.com/Web-Feet/coasterthemes/tree/master/coaster2017/views/emails)
